//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsicoManager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Agenda = new HashSet<Agenda>();
            this.Pagamentos = new HashSet<Pagamento>();
        }
    
        public int PacienteId { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public string RG { get; set; }
        public string CPF { get; set; }
        public System.DateTime DataInclusao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string Sexo { get; set; }
        public string UF { get; set; }
        public string Cidade { get; set; }
        public string Bairro { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Observacao { get; set; }
        public string Telefone1 { get; set; }
        public string Telefone2 { get; set; }
        public string Ocupacao { get; set; }
        public string Anotacoes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda> Agenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagamento> Pagamentos { get; set; }
    }
}
