//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsicoManager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public int PagamentoId { get; set; }
        public int PacienteId { get; set; }
        public decimal Valor { get; set; }
        public bool Pago { get; set; }
        public System.DateTime DataPagamento { get; set; }
        public System.DateTime DataLimitePagamento { get; set; }
        public System.DateTime DataInclusao { get; set; }
        public Nullable<int> AgendaId { get; set; }
        public string Observacao { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Agenda Agendum { get; set; }
    }
}
